// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SitoLtb.Data;

#nullable disable

namespace SitoLtb.Migrations.LtbDb
{
    [DbContext(typeof(LtbDbContext))]
    partial class LtbDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventoLavoratore", b =>
                {
                    b.Property<int>("FkidEvento")
                        .HasColumnType("int")
                        .HasColumnName("FKidEvento");

                    b.Property<int>("FkidLavoratore")
                        .HasColumnType("int")
                        .HasColumnName("FKidLavoratore");

                    b.HasKey("FkidEvento", "FkidLavoratore");

                    b.HasIndex("FkidLavoratore");

                    b.ToTable("EventoLavoratore", (string)null);
                });

            modelBuilder.Entity("EventoPartecipante", b =>
                {
                    b.Property<int>("FkidEvento")
                        .HasColumnType("int")
                        .HasColumnName("FKidEvento");

                    b.Property<int>("FkidPartecipante")
                        .HasColumnType("int")
                        .HasColumnName("FKidPartecipante");

                    b.HasKey("FkidEvento", "FkidPartecipante");

                    b.HasIndex("FkidPartecipante");

                    b.ToTable("EventoPartecipante", (string)null);
                });

            modelBuilder.Entity("PoloEvento", b =>
                {
                    b.Property<int>("FkidPolo")
                        .HasColumnType("int")
                        .HasColumnName("FKidPolo");

                    b.Property<int>("FkidEvento")
                        .HasColumnType("int")
                        .HasColumnName("FKidEvento");

                    b.HasKey("FkidPolo", "FkidEvento");

                    b.HasIndex("FkidEvento");

                    b.ToTable("PoloEvento", (string)null);
                });

            modelBuilder.Entity("SitoLtb.Data.Agonisti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Allievo")
                        .HasColumnType("bit")
                        .HasColumnName("allievo");

                    b.Property<DateOnly?>("AnnoPrimaIscrizione")
                        .HasColumnType("date")
                        .HasColumnName("annoPrimaIscrizione");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cognome");

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("email");

                    b.Property<int>("FkidPolo")
                        .HasColumnType("int")
                        .HasColumnName("FKidPolo");

                    b.Property<string>("IdFide")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("idFide");

                    b.Property<string>("IdFsi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("idFsi");

                    b.Property<bool?>("Lavoratore")
                        .HasColumnType("bit")
                        .HasColumnName("lavoratore");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.Property<bool?>("Partecipante")
                        .HasColumnType("bit")
                        .HasColumnName("partecipante");

                    b.Property<bool?>("Socio")
                        .HasColumnType("bit")
                        .HasColumnName("socio");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoTessera")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipoTessera");

                    b.HasKey("Id")
                        .HasName("PK__Agonisti__3213E83F2CC2EB13");

                    b.HasIndex("FkidPolo");

                    b.ToTable("Agonisti", (string)null);
                });

            modelBuilder.Entity("SitoLtb.Data.Allievi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Agonista")
                        .HasColumnType("bit")
                        .HasColumnName("agonista");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cognome");

                    b.Property<int?>("Elo")
                        .HasColumnType("int")
                        .HasColumnName("elo");

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("email");

                    b.Property<int?>("Eta")
                        .HasColumnType("int")
                        .HasColumnName("eta");

                    b.Property<bool?>("Lavoratore")
                        .HasColumnType("bit")
                        .HasColumnName("lavoratore");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.Property<bool?>("Partecipante")
                        .HasColumnType("bit")
                        .HasColumnName("partecipante");

                    b.Property<bool?>("Socio")
                        .HasColumnType("bit")
                        .HasColumnName("socio");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("PK__Allievi__3213E83F25A9DF33");

                    b.ToTable("Allievi", (string)null);
                });

            modelBuilder.Entity("SitoLtb.Data.AnnoAgonistico", b =>
                {
                    b.Property<int>("Anno")
                        .HasColumnType("int")
                        .HasColumnName("anno");

                    b.Property<int?>("EloBlitz1gen")
                        .HasColumnType("int");

                    b.Property<int?>("EloBlitz1giu")
                        .HasColumnType("int");

                    b.Property<int?>("EloBlitz1mar")
                        .HasColumnType("int");

                    b.Property<int?>("EloBlitz1set")
                        .HasColumnType("int");

                    b.Property<int?>("EloRapid1gen")
                        .HasColumnType("int");

                    b.Property<int?>("EloRapid1giu")
                        .HasColumnType("int");

                    b.Property<int?>("EloRapid1mar")
                        .HasColumnType("int");

                    b.Property<int?>("EloRapid1set")
                        .HasColumnType("int");

                    b.Property<int?>("EloStandard1giu")
                        .HasColumnType("int");

                    b.Property<int?>("EloStandard1mar")
                        .HasColumnType("int");

                    b.Property<int?>("EloStandard1set")
                        .HasColumnType("int");

                    b.Property<int?>("Elostandard1gen")
                        .HasColumnType("int");

                    b.Property<int>("FkidAgonista")
                        .HasColumnType("int")
                        .HasColumnName("FKidAgonista");

                    b.Property<int?>("NTorneiSvolti")
                        .HasColumnType("int")
                        .HasColumnName("nTorneiSvolti");

                    b.Property<int?>("VariazioneElo")
                        .HasColumnType("int")
                        .HasColumnName("variazioneElo");

                    b.HasIndex("FkidAgonista");

                    b.ToTable("AnnoAgonistico", (string)null);
                });

            modelBuilder.Entity("SitoLtb.Data.ClasseAllievo", b =>
                {
                    b.Property<int>("FkidClasse")
                        .HasColumnType("int")
                        .HasColumnName("FKidClasse");

                    b.Property<int>("FkidAllievo")
                        .HasColumnType("int")
                        .HasColumnName("FKidAllievo");

                    b.Property<DateOnly>("Anno")
                        .HasColumnType("date")
                        .HasColumnName("anno");

                    b.HasKey("FkidClasse", "FkidAllievo", "Anno")
                        .HasName("PKClasseAllievo");

                    b.HasIndex("FkidAllievo");

                    b.ToTable("ClasseAllievo", (string)null);
                });

            modelBuilder.Entity("SitoLtb.Data.ClasseLavoratore", b =>
                {
                    b.Property<int>("FkidClasse")
                        .HasColumnType("int")
                        .HasColumnName("FKidClasse");

                    b.Property<int>("FkidLavoratore")
                        .HasColumnType("int")
                        .HasColumnName("FKidLavoratore");

                    b.Property<DateOnly>("Anno")
                        .HasColumnType("date")
                        .HasColumnName("anno");

                    b.HasKey("FkidClasse", "FkidLavoratore", "Anno")
                        .HasName("PKClasseLavoratore");

                    b.HasIndex("FkidLavoratore");

                    b.ToTable("ClasseLavoratore", (string)null);
                });

            modelBuilder.Entity("SitoLtb.Data.Classi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Argomento")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("argomento")
                        .IsFixedLength();

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<int>("FkidScuola")
                        .HasColumnType("int")
                        .HasColumnName("FKidScuola");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("PK__Classi__3213E83F30F9F908");

                    b.HasIndex("FkidScuola");

                    b.ToTable("Classi", (string)null);
                });

            modelBuilder.Entity("SitoLtb.Data.ControlliRicorrenti", b =>
                {
                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("data")
                        .IsFixedLength();

                    b.Property<int>("Noccorrenze")
                        .HasColumnType("int")
                        .HasColumnName("noccorrenze");

                    b.Property<string>("NomeTabella")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nomeTabella");

                    b.ToTable("ControlliRicorrenti", (string)null);
                });

            modelBuilder.Entity("SitoLtb.Data.Cooperazioni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DataFineCooperazione")
                        .HasColumnType("date")
                        .HasColumnName("dataFineCooperazione");

                    b.Property<DateOnly>("DataInizioCooperazione")
                        .HasColumnType("date")
                        .HasColumnName("dataInizioCooperazione");

                    b.Property<int>("FkpoloId")
                        .HasColumnType("int")
                        .HasColumnName("FKPoloId");

                    b.Property<int>("FkrealtaEsternaId")
                        .HasColumnType("int")
                        .HasColumnName("FKRealtaEsternaId");

                    b.Property<string>("Tipologia")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipologia");

                    b.HasKey("Id")
                        .HasName("PK__Cooperaz__3213E83F76031D81");

                    b.HasIndex("FkpoloId");

                    b.HasIndex("FkrealtaEsternaId");

                    b.ToTable("Cooperazioni", (string)null);
                });

            modelBuilder.Entity("SitoLtb.Data.Eventi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classifica")
                        .HasColumnType("xml")
                        .HasColumnName("classifica");

                    b.Property<int?>("Costo")
                        .HasColumnType("int")
                        .HasColumnName("costo");

                    b.Property<DateOnly?>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("LinkBando")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("linkBando");

                    b.Property<string>("Luogo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("luogo");

                    b.Property<string>("Nome")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nome");

                    b.Property<bool?>("Omologato")
                        .HasColumnType("bit")
                        .HasColumnName("omologato");

                    b.Property<string>("Tipologia")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("tipologia");

                    b.HasKey("Id")
                        .HasName("PK__Eventi__3213E83FB73FAEA3");

                    b.ToTable("Eventi", null, t =>
                        {
                            t.HasTrigger("insert_table_eventopolo");

                            t.HasTrigger("trg_DeletePoloEvento");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SitoLtb.Data.Lavoratori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Agonista")
                        .HasColumnType("bit")
                        .HasColumnName("agonista");

                    b.Property<bool?>("Allievo")
                        .HasColumnType("bit")
                        .HasColumnName("allievo");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cognome");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<int?>("Eta")
                        .HasColumnType("int")
                        .HasColumnName("eta");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nome");

                    b.Property<bool?>("Partecipante")
                        .HasColumnType("bit")
                        .HasColumnName("partecipante");

                    b.Property<string>("Provenienza")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("provenienza");

                    b.Property<bool?>("Socio")
                        .HasColumnType("bit")
                        .HasColumnName("socio");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipologiaLavoratore")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipologiaLavoratore");

                    b.HasKey("Id")
                        .HasName("PK__Lavorato__3213E83F53686E39");

                    b.ToTable("Lavoratori", (string)null);
                });

            modelBuilder.Entity("SitoLtb.Data.Partecipanti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Agonista")
                        .HasColumnType("bit")
                        .HasColumnName("agonista");

                    b.Property<bool?>("Allievo")
                        .HasColumnType("bit")
                        .HasColumnName("allievo");

                    b.Property<string>("Circolo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("circolo");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cognome");

                    b.Property<int?>("Elo")
                        .HasColumnType("int")
                        .HasColumnName("elo");

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("email");

                    b.Property<int?>("Eta")
                        .HasColumnType("int")
                        .HasColumnName("eta");

                    b.Property<bool?>("Lavoratore")
                        .HasColumnType("bit")
                        .HasColumnName("lavoratore");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nome");

                    b.Property<bool?>("PrimoEvento")
                        .HasColumnType("bit")
                        .HasColumnName("primoEvento");

                    b.Property<bool?>("Socio")
                        .HasColumnType("bit")
                        .HasColumnName("socio");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("PK__Partecip__3213E83F855F149E");

                    b.ToTable("Partecipanti", null, t =>
                        {
                            t.HasTrigger("InsertIntoEventoPartecipante");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SitoLtb.Data.Persone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Agonista")
                        .HasColumnType("bit")
                        .HasColumnName("agonista");

                    b.Property<bool?>("Allievo")
                        .HasColumnType("bit")
                        .HasColumnName("allievo");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("cognome")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("email");

                    b.Property<int>("Eta")
                        .HasColumnType("int")
                        .HasColumnName("eta");

                    b.Property<bool?>("Lavoratore")
                        .HasColumnType("bit")
                        .HasColumnName("lavoratore");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("nome")
                        .IsFixedLength();

                    b.Property<bool?>("Partecipante")
                        .HasColumnType("bit")
                        .HasColumnName("partecipante");

                    b.Property<bool?>("Socio")
                        .HasColumnType("bit")
                        .HasColumnName("socio");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("PK__Persone__3213E83F35604BA9");

                    b.ToTable("Persone", (string)null);
                });

            modelBuilder.Entity("SitoLtb.Data.Poli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Indirizzo")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("indirizzo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome");

                    b.Property<string>("Piva")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("piva")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__Poli__3213E83FF4797DCC");

                    b.ToTable("Poli", (string)null);
                });

            modelBuilder.Entity("SitoLtb.Data.PoloScuola", b =>
                {
                    b.Property<int>("FkidPolo")
                        .HasColumnType("int")
                        .HasColumnName("FKidPolo");

                    b.Property<int>("FkidScuola")
                        .HasColumnType("int")
                        .HasColumnName("FKidScuola");

                    b.Property<int>("Anno")
                        .HasColumnType("int")
                        .HasColumnName("anno");

                    b.HasKey("FkidPolo", "FkidScuola", "Anno")
                        .HasName("PKPoloScuola");

                    b.HasIndex("FkidScuola");

                    b.ToTable("PoloScuola", (string)null);
                });

            modelBuilder.Entity("SitoLtb.Data.RealtaEsternaPersona", b =>
                {
                    b.Property<int>("FkidRealtaEsterna")
                        .HasColumnType("int")
                        .HasColumnName("FKidRealtaEsterna");

                    b.Property<int>("FkidPersona")
                        .HasColumnType("int")
                        .HasColumnName("FKidPersona");

                    b.Property<DateOnly>("Anno")
                        .HasColumnType("date")
                        .HasColumnName("anno");

                    b.HasKey("FkidRealtaEsterna", "FkidPersona", "Anno")
                        .HasName("PKRealtaEsternaPersona");

                    b.HasIndex("FkidPersona");

                    b.ToTable("RealtaEsternaPersona", (string)null);
                });

            modelBuilder.Entity("SitoLtb.Data.RealtaEsterne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("nome")
                        .IsFixedLength();

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("Tipologia")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("tipologia")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PK__RealtaEs__3213E83FAE65C21B");

                    b.ToTable("RealtaEsterne", (string)null);
                });

            modelBuilder.Entity("SitoLtb.Data.Scuole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("indirizzo")
                        .IsFixedLength();

                    b.Property<string>("Mail")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mail");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("nome")
                        .IsFixedLength();

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipologiaScuola")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("tipologiaScuola");

                    b.HasKey("Id")
                        .HasName("PK__Scuole__3213E83F4468ADC2");

                    b.ToTable("Scuole", null, t =>
                        {
                            t.HasTrigger("InsertIntoPoloScuola");

                            t.HasTrigger("trg_DeletePoloScuola");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SitoLtb.Data.Soci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Agonista")
                        .HasColumnType("bit")
                        .HasColumnName("agonista");

                    b.Property<bool?>("Allievo")
                        .HasColumnType("bit")
                        .HasColumnName("allievo");

                    b.Property<DateOnly?>("AnnoPrimaIscrizione")
                        .HasColumnType("date")
                        .HasColumnName("annoPrimaIscrizione");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cognome");

                    b.Property<int?>("Elo")
                        .HasColumnType("int")
                        .HasColumnName("elo");

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("email");

                    b.Property<int?>("Eta")
                        .HasColumnType("int")
                        .HasColumnName("eta");

                    b.Property<bool?>("Lavoratore")
                        .HasColumnType("bit")
                        .HasColumnName("lavoratore");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nome");

                    b.Property<bool?>("Partecipante")
                        .HasColumnType("bit")
                        .HasColumnName("partecipante");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipologiaIscrizione")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipologiaIscrizione");

                    b.HasKey("Id")
                        .HasName("PK__Soci__3213E83F6472C5CB");

                    b.ToTable("Soci", null, t =>
                        {
                            t.HasTrigger("after_insert_on_soci");

                            t.HasTrigger("trg_DeleteSocioPolo");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("SitoLtb.Data.SocioPolo", b =>
                {
                    b.Property<int>("FkidPolo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("FKidPolo");

                    b.Property<int>("FkidSocio")
                        .HasColumnType("int")
                        .HasColumnName("FKidSocio");

                    b.Property<int>("Anno")
                        .HasColumnType("int");

                    b.HasKey("FkidPolo", "FkidSocio", "Anno")
                        .HasName("Anno");

                    b.HasIndex("FkidSocio");

                    b.ToTable("SocioPolo", (string)null);
                });

            modelBuilder.Entity("EventoLavoratore", b =>
                {
                    b.HasOne("SitoLtb.Data.Eventi", null)
                        .WithMany()
                        .HasForeignKey("FkidEvento")
                        .IsRequired()
                        .HasConstraintName("FK__EventoLav__FKidE__74AE54BC");

                    b.HasOne("SitoLtb.Data.Lavoratori", null)
                        .WithMany()
                        .HasForeignKey("FkidLavoratore")
                        .IsRequired()
                        .HasConstraintName("FK__EventoLav__FKidL__75A278F5");
                });

            modelBuilder.Entity("EventoPartecipante", b =>
                {
                    b.HasOne("SitoLtb.Data.Eventi", null)
                        .WithMany()
                        .HasForeignKey("FkidEvento")
                        .IsRequired()
                        .HasConstraintName("FK__EventoPar__FKidE__6EF57B66");

                    b.HasOne("SitoLtb.Data.Partecipanti", null)
                        .WithMany()
                        .HasForeignKey("FkidPartecipante")
                        .IsRequired()
                        .HasConstraintName("FK__EventoPar__FKidP__6FE99F9F");
                });

            modelBuilder.Entity("PoloEvento", b =>
                {
                    b.HasOne("SitoLtb.Data.Eventi", null)
                        .WithMany()
                        .HasForeignKey("FkidEvento")
                        .IsRequired()
                        .HasConstraintName("FK__PoloEvent__FKidE__6A30C649");

                    b.HasOne("SitoLtb.Data.Poli", null)
                        .WithMany()
                        .HasForeignKey("FkidPolo")
                        .IsRequired()
                        .HasConstraintName("FK__PoloEvent__FKidP__693CA210");
                });

            modelBuilder.Entity("SitoLtb.Data.Agonisti", b =>
                {
                    b.HasOne("SitoLtb.Data.Poli", "FkidPoloNavigation")
                        .WithMany("Agonistis")
                        .HasForeignKey("FkidPolo")
                        .IsRequired()
                        .HasConstraintName("Fk_AgonistaPolo");

                    b.Navigation("FkidPoloNavigation");
                });

            modelBuilder.Entity("SitoLtb.Data.AnnoAgonistico", b =>
                {
                    b.HasOne("SitoLtb.Data.Agonisti", "FkidAgonistaNavigation")
                        .WithMany()
                        .HasForeignKey("FkidAgonista")
                        .IsRequired()
                        .HasConstraintName("FK__AnnoAgoni__FKidA__3493CFA7");

                    b.Navigation("FkidAgonistaNavigation");
                });

            modelBuilder.Entity("SitoLtb.Data.ClasseAllievo", b =>
                {
                    b.HasOne("SitoLtb.Data.Allievi", "FkidAllievoNavigation")
                        .WithMany("ClasseAllievos")
                        .HasForeignKey("FkidAllievo")
                        .IsRequired()
                        .HasConstraintName("FK__ClasseAll__FKidA__07C12930");

                    b.HasOne("SitoLtb.Data.Classi", "FkidClasseNavigation")
                        .WithMany("ClasseAllievos")
                        .HasForeignKey("FkidClasse")
                        .IsRequired()
                        .HasConstraintName("FK__ClasseAll__FKidC__06CD04F7");

                    b.Navigation("FkidAllievoNavigation");

                    b.Navigation("FkidClasseNavigation");
                });

            modelBuilder.Entity("SitoLtb.Data.ClasseLavoratore", b =>
                {
                    b.HasOne("SitoLtb.Data.Classi", "FkidClasseNavigation")
                        .WithMany("ClasseLavoratores")
                        .HasForeignKey("FkidClasse")
                        .IsRequired()
                        .HasConstraintName("FK__ClasseLav__FKidC__01142BA1");

                    b.HasOne("SitoLtb.Data.Lavoratori", "FkidLavoratoreNavigation")
                        .WithMany("ClasseLavoratores")
                        .HasForeignKey("FkidLavoratore")
                        .IsRequired()
                        .HasConstraintName("FK__ClasseLav__FKidL__02084FDA");

                    b.Navigation("FkidClasseNavigation");

                    b.Navigation("FkidLavoratoreNavigation");
                });

            modelBuilder.Entity("SitoLtb.Data.Classi", b =>
                {
                    b.HasOne("SitoLtb.Data.Scuole", "FkidScuolaNavigation")
                        .WithMany("Classis")
                        .HasForeignKey("FkidScuola")
                        .IsRequired()
                        .HasConstraintName("FK__Classi__FKidScuo__7E37BEF6");

                    b.Navigation("FkidScuolaNavigation");
                });

            modelBuilder.Entity("SitoLtb.Data.Cooperazioni", b =>
                {
                    b.HasOne("SitoLtb.Data.Poli", "Fkpolo")
                        .WithMany("Cooperazionis")
                        .HasForeignKey("FkpoloId")
                        .IsRequired()
                        .HasConstraintName("FK__Cooperazi__FKPol__1F98B2C1");

                    b.HasOne("SitoLtb.Data.RealtaEsterne", "FkrealtaEsterna")
                        .WithMany("Cooperazionis")
                        .HasForeignKey("FkrealtaEsternaId")
                        .IsRequired()
                        .HasConstraintName("FK__Cooperazi__FKRea__208CD6FA");

                    b.Navigation("Fkpolo");

                    b.Navigation("FkrealtaEsterna");
                });

            modelBuilder.Entity("SitoLtb.Data.PoloScuola", b =>
                {
                    b.HasOne("SitoLtb.Data.Poli", "FkidPoloNavigation")
                        .WithMany("PoloScuolas")
                        .HasForeignKey("FkidPolo")
                        .IsRequired()
                        .HasConstraintName("FK__PoloScuol__FKidP__7A672E12");

                    b.HasOne("SitoLtb.Data.Scuole", "FkidScuolaNavigation")
                        .WithMany("PoloScuolas")
                        .HasForeignKey("FkidScuola")
                        .IsRequired()
                        .HasConstraintName("FK__PoloScuol__FKidS__7B5B524B");

                    b.Navigation("FkidPoloNavigation");

                    b.Navigation("FkidScuolaNavigation");
                });

            modelBuilder.Entity("SitoLtb.Data.RealtaEsternaPersona", b =>
                {
                    b.HasOne("SitoLtb.Data.Persone", "FkidPersonaNavigation")
                        .WithMany("RealtaEsternaPersonas")
                        .HasForeignKey("FkidPersona")
                        .IsRequired()
                        .HasConstraintName("FK__RealtaEst__FKidP__66603565");

                    b.HasOne("SitoLtb.Data.RealtaEsterne", "FkidRealtaEsternaNavigation")
                        .WithMany("RealtaEsternaPersonas")
                        .HasForeignKey("FkidRealtaEsterna")
                        .IsRequired()
                        .HasConstraintName("FK__RealtaEst__FKidR__656C112C");

                    b.Navigation("FkidPersonaNavigation");

                    b.Navigation("FkidRealtaEsternaNavigation");
                });

            modelBuilder.Entity("SitoLtb.Data.SocioPolo", b =>
                {
                    b.HasOne("SitoLtb.Data.Poli", "FkidPoloNavigation")
                        .WithMany("SocioPolos")
                        .HasForeignKey("FkidPolo")
                        .IsRequired()
                        .HasConstraintName("FK__SocioPolo__FKidP__5FB337D6");

                    b.HasOne("SitoLtb.Data.Soci", "FkidSocioNavigation")
                        .WithMany("SocioPolos")
                        .HasForeignKey("FkidSocio")
                        .IsRequired()
                        .HasConstraintName("FK__SocioPolo__FKidS__60A75C0F");

                    b.Navigation("FkidPoloNavigation");

                    b.Navigation("FkidSocioNavigation");
                });

            modelBuilder.Entity("SitoLtb.Data.Allievi", b =>
                {
                    b.Navigation("ClasseAllievos");
                });

            modelBuilder.Entity("SitoLtb.Data.Classi", b =>
                {
                    b.Navigation("ClasseAllievos");

                    b.Navigation("ClasseLavoratores");
                });

            modelBuilder.Entity("SitoLtb.Data.Lavoratori", b =>
                {
                    b.Navigation("ClasseLavoratores");
                });

            modelBuilder.Entity("SitoLtb.Data.Persone", b =>
                {
                    b.Navigation("RealtaEsternaPersonas");
                });

            modelBuilder.Entity("SitoLtb.Data.Poli", b =>
                {
                    b.Navigation("Agonistis");

                    b.Navigation("Cooperazionis");

                    b.Navigation("PoloScuolas");

                    b.Navigation("SocioPolos");
                });

            modelBuilder.Entity("SitoLtb.Data.RealtaEsterne", b =>
                {
                    b.Navigation("Cooperazionis");

                    b.Navigation("RealtaEsternaPersonas");
                });

            modelBuilder.Entity("SitoLtb.Data.Scuole", b =>
                {
                    b.Navigation("Classis");

                    b.Navigation("PoloScuolas");
                });

            modelBuilder.Entity("SitoLtb.Data.Soci", b =>
                {
                    b.Navigation("SocioPolos");
                });
#pragma warning restore 612, 618
        }
    }
}
